on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        id: test
        uses: markjm/gh-actions-repro/action@ceebc81ab968c9ef6ca4dd5e18b2b8370570dfec
